{
 "title": "Test dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Климат / Давление",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "zhub2_metrics{type=\"pressure\",job=\"zhub2\",device=~\"КлиматБалкон|Climat1\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Давление",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zhub2_metrics{job=\"zhub2\", type=\"pressure\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Датчики/Реле Кухня",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "zhub2_metrics{type=\"motion\",job=\"zhub2\",device=~\"КухняПрисутствие1\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "zhub2_metrics{type=\"relay\",job=\"zhub2\", device=~\"КухняСвет\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "zhub2_metrics{type=\"relay\",job=\"zhub2\", device=~\"КухняВент\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "zhub2_metrics{type=\"motion\",job=\"zhub2\",device=~\"КухняДвижение5\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Датчики/Реле Коридор",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "zhub2_metrics{device=~\"КоридорДвижение1\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "zhub2_metrics{type=\"relay\",job=\"zhub2\",device=~\"КоридорСвет\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "zhub2_metrics{type=\"motion\",job=\"zhub2\",device=~\"КоридорДвижение3\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "zhub2_metrics{type=\"motion\",job=\"zhub2\",device=~\"ПрихожаяДвижение\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Датчики/Реле Туалет",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "zhub2_metrics{type=\"door\",job=\"zhub2\",device=~\"ТуалетДатчик|MToilet\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "zhub2_metrics{type=\"relay\",job=\"zhub2\", device=~\"ТулетЗанят|RToilet\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Все датчики движения",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "zhub2_metrics{type=\"motion\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "zhub2_metrics{type=\"door\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}